# Generated by Django 4.0.4 on 2022-05-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=25)),
                ('data', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
