# Generated by Django 4.0.5 on 2022-06-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_cadeira_descricao_alter_projeto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(max_length=600),
        ),
    ]
